#!/usr/bin/env bash
# Regenerates the reviewable source diff of the S1b package against the ACCEPTED R4 snapshot (M1-SAFE-STOP-RECOVERY-01/runner-r4-source) and verifies it:
#   r4-to-s1b.patch        unified diff R4 -> S1b (modified, new and removed files; apply with `patch -p1 --binary`)
#   s1b-vs-r4-files.txt    one line per file: IDENTICAL | MODIFIED | NEW | REMOVED  (+ SHA-256 of the S1b side)
# Verification: the R4 snapshot copy + patch + regenerated code sums == the S1b source tree, byte for byte.
# Usage (from the repository root): bash make-s1b-diff.sh <evidence dir M1-STAGING-R3-SMOKE-PREP-02> <accepted R4 snapshot dir>
set -euo pipefail
export LC_ALL=C
EV=$(cd "$1" && pwd); R4=$(cd "$2" && pwd); S1B="$EV/package-s1b-source"
WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
list() { (cd "$1" && find . -type f ! -name CODE-SHA256SUMS.txt ! -name .gitattributes | sed 's|^\./||' | sort); }
list "$R4" > "$WORK/r4.txt"; list "$S1B" > "$WORK/s1b.txt"
: > "$EV/r4-to-s1b.patch"; : > "$EV/s1b-vs-r4-files.txt"
while IFS= read -r f; do
  if ! grep -qxF -- "$f" "$WORK/s1b.txt"; then
    diff -u --label "a/$f" --label /dev/null "$R4/$f" /dev/null >> "$EV/r4-to-s1b.patch" || [ $? -eq 1 ]
    echo "REMOVED   -  $f" >> "$EV/s1b-vs-r4-files.txt"
  fi
done < "$WORK/r4.txt"
while IFS= read -r f; do
  h=$(sha256sum -b "$S1B/$f" | cut -d' ' -f1)
  if ! grep -qxF -- "$f" "$WORK/r4.txt"; then
    diff -u --label /dev/null --label "b/$f" /dev/null "$S1B/$f" >> "$EV/r4-to-s1b.patch" || [ $? -eq 1 ]
    echo "NEW       $h  $f" >> "$EV/s1b-vs-r4-files.txt"
  elif cmp -s "$R4/$f" "$S1B/$f"; then
    echo "IDENTICAL $h  $f" >> "$EV/s1b-vs-r4-files.txt"
  else
    diff -u --label "a/$f" --label "b/$f" "$R4/$f" "$S1B/$f" >> "$EV/r4-to-s1b.patch" || [ $? -eq 1 ]
    echo "MODIFIED  $h  $f" >> "$EV/s1b-vs-r4-files.txt"
  fi
done < "$WORK/s1b.txt"
# verification: R4 + patch == S1b (sums regenerated by the package's own tool)
mkdir -p "$WORK/r4copy"; (cd "$R4" && tar -cf - .) | (cd "$WORK/r4copy" && tar -xf -)
(cd "$WORK/r4copy" && patch -p1 --binary -s -E < "$EV/r4-to-s1b.patch")
(cd "$WORK/r4copy" && rm -f CODE-SHA256SUMS.txt && node tests/make-code-sums.mjs >/dev/null)
diff -rq "$WORK/r4copy" "$S1B" && echo "S1B_PATCH_APPLY_BYTE_COMPARE_OK identical=$(grep -c '^IDENTICAL' "$EV/s1b-vs-r4-files.txt") modified=$(grep -c '^MODIFIED' "$EV/s1b-vs-r4-files.txt") new=$(grep -c '^NEW' "$EV/s1b-vs-r4-files.txt") removed=$(grep -c '^REMOVED' "$EV/s1b-vs-r4-files.txt")"
